課題2　実装
golfhiro/mokumoku pull request #3
Opened 2023-01-31 12:21 UTC by golfhiro

ご確認よろしくお願いします。

2023-01-31 13:12 UTC, Tsuchiya2 commented
こちらの連絡不備ですみません🙇

以下のspecが通るように実装をお願いします。実装後、テスト結果のスクリーンショットと選択した事業課題を記載して提出をお願いいたします。

https://esa-storage-tokyo.s3-ap-northeast-1.amazonaws.com/uploads/production/attachments/2315/2022/12/01/126058/2b055823-1710-4752-bb05-85adef7a05a8.zip

```
【実装方針】
- ユーザー登録時に手入力やチェックボックス入力ではなく、セレクト形式で性別登録できる。
- イベント作成画面にOnly womanのチェックボックスにチェックを入れるだけで女性限定イベントを作できる。
- ユーザーが女性以外の場合、イベント作成時にOnly womanは表示されず、女性限定イベントが作成できない。
- 女性限定イベントには女性のみが参加できる。
- 女性以外の場合、女性限定イベントの詳細ページを開いた際に「このもくもく会に参加する」が表示されない。
- 女性限定イベントは一覧・詳細画面にて「女性限定」が表記される。

【注意点】
- イベントが女性限定であるかを判定するカラムは"only_woman"とする
- ユーザーの性別登録のカラムは"gender"とする
- ユーザー登録時の性別のセレクト部分はenumを使って「その他・男性・女性」が表示される（その際に特に操作が無かれば"その他"が選択される）
    
【Gemfile】
Testグループに以下のgemを追加
- gem 'capybara', '~> 3.23'
- gem 'selenium-webdriver'
- gem 'webdrivers' 
```

2023-01-31 13:15 UTC, golfhiro commented
承知しました。
修正します。

2023-02-02 05:12 UTC, golfhiro commented
ご確認よろしくお願いします。

事業課題
サービス登録者数の内、男性60%に対して、女性は40%。一方で、サービス内のもくもく会に参加した人の比率は、男性90%：女性10%と大きな差が出ています。もっと女性が使いやすいようなサービス設計にする必要があるのではないか？

[https://i.gyazo.com/a9b8d9de7a84c1cc8c085c04ae66e586.png](url)

2023-02-02 12:20 UTC, busitora requested changes
コメントしました！

2023-02-02 12:20 UTC, busitora commented on app/views/events/_event.html.erb
> +      <% if event.only_woman == true %>
`only_woman?` としましょう

== true は not good です

2023-02-02 12:20 UTC, busitora commented on app/views/events/_form.html.erb
> +  <% if current_user.gender == 'woman' %>
上記同様、メソッド化してください

2023-02-02 12:20 UTC, busitora commented on app/views/events/show.html.erb
> +          <% if @event.only_woman == true %>
上記同様、メソッド化してください

2023-02-02 12:20 UTC, busitora commented on app/views/events/show.html.erb
> +                    <% when @event.only_woman == true && current_user.gender == 'woman' %>
&& が true となる様に引数を定義したメソッド を model に記載おねがいします。

また、 case 文ではなく if文でおねがいします。

2023-02-02 12:20 UTC, busitora commented on app/views/events/show.html.erb
> +                    <% when @event.only_woman == false %>
上記同様、メソッド化してください

2023-02-02 16:03 UTC, golfhiro commented
修正しました。
ご確認よろしくお願いします。

事業課題
サービス登録者数の内、男性60%に対して、女性は40%。一方で、サービス内のもくもく会に参加した人の比率は、男性90%：女性10%と大きな差が出ています。もっと女性が使いやすいようなサービス設計にする必要があるのではないか？

[![Image from Gyazo](https://i.gyazo.com/a9b8d9de7a84c1cc8c085c04ae66e586.png)](https://gyazo.com/a9b8d9de7a84c1cc8c085c04ae66e586)

2023-02-03 11:55 UTC, takyyk commented
@golfhiro 
LGTMです！

2023-02-03 13:56 UTC, merged